# Generate a list of 200 applicants

# 1. Loading packages and dataset

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-darkgrid')

df = pd.read_csv('score_with_all_results.csv', index_col=[0])

We sort our list by 'outcome_profit' - 'outcome_profit_damage' so we see who will realize the most profit for the hotel.

In [2]:
df['profit_after_damage_reduction'] = (df['outcome_profit']-df['outcome_damage_amount'])
df.sort_values(by = ['profit_after_damage_reduction'], ascending=False)

,income_am,profit_last_am,profit_am,damage_am,damage_inc,crd_lim_rec,credit_use_ic,gluten_ic,lactose_ic,insurance_ic,...,sect_empl_0.0,sect_empl_1.0,sect_empl_2.0,sect_empl_4.0,sect_empl_6.0,sect_empl_3.0,outcome_profit,outcome_damage_inc,outcome_damage_amount,profit_after_damage_reduction
81,2.516094,1.041242,3.665813,-0.409033,-0.452286,-1.094296,-0.208160,0.0,0.0,0.0,...,1,0,0,0,0,0,9.722991,0,0.000000,9.722991
431,2.610292,0.387654,3.860555,-0.409033,1.216375,-1.094296,-0.208160,0.0,0.0,0.0,...,0,1,0,0,0,0,9.604190,0,0.000000,9.604190
256,2.732761,-0.038515,3.889893,2.176932,2.885036,1.003314,-0.208160,0.0,1.0,0.0,...,1,0,0,0,0,0,9.513949,0,0.000000,9.513949
48,2.707062,0.863705,3.125142,-0.409033,-0.452286,1.003314,-0.208160,0.0,0.0,0.0,...,1,0,0,0,0,0,8.957491,0,0.000000,8.957491
84,1.749793,1.219927,1.728799,2.829679,4.553696,0.966799,4.804002,0.0,1.0,1.0,...,1,0,0,0,0,0,8.845885,0,0.000000,8.845885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,0.223492,1.344227,0.966109,-0.409033,2.885036,1.140668,-0.208160,0.0,0.0,1.0,...,1,0,0,0,0,0,7.193025,1,6.805813,0.387212
441,0.861502,0.224113,0.203601,-0.409033,-0.452286,0.898656,-0.208160,0.0,0.0,1.0,...,1,0,0,0,0,0,6.925340,1,6.540952,0.384387
247,-0.537142,-0.350854,-0.409036,-0.409033,-0.452286,0.839130,-0.208160,0.0,0.0,0.0,...,0,1,0,0,0,0,6.843975,1,6.475394,0.368581
380,-0.001601,0.497031,-0.326734,-0.409033,-0.452286,0.923612,-0.208160,0.0,0.0,1.0,...,1,0,0,0,0,0,6.814042,1,6.495743,0.318300
20,-0.638727,-1.142158,0.151141,-0.409033,-0.452286,0.759442,-0.208160,0.0,0.0,1.0,...,1,0,0,0,0,0,6.731605,1,6.624166,0.107438

No we take the first 200 people as past applicants

In [3]:
passed_applicants = df.iloc[:199,:]
passed_applicants.to_csv('final_list.csv')